# Generated by Django 5.0.1 on 2024-01-10 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_telegrambot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='projects.project'),
        ),
    ]
