# Generated by Django 5.0.1 on 2024-01-10 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_telegrambot_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telegram Bot', 'verbose_name_plural': 'Telegram Bots'},
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
