# Generated by Django 5.0.1 on 2024-01-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_telegrambot_options_telegrambot_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='isWebhookSet',
            field=models.BooleanField(default=False, verbose_name='Webhook is set'),
        ),
    ]
