# Generated by Django 5.0.1 on 2024-01-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_telegrambot_iswebhookset'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
    ]
