# Generated by Django 5.0.1 on 2024-01-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_iswebhookset_telegrambot_is_webhook_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
    ]
