# Generated by Django 5.0.1 on 2024-01-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_router_project_router'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Congigs',
                'ordering': ['name'],
            },
        ),
    ]
