# Generated by Django 5.0.1 on 2024-01-15 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_telegrambotconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotconfig',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='projects.telegrambot'),
            preserve_default=False,
        ),
    ]
