# Generated by Django 5.0.1 on 2024-01-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_telegrambotconfig_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='handler',
            field=models.CharField(max_length=50, unique=True, verbose_name='handler'),
        ),
    ]
