# Generated by Django 5.0.1 on 2024-01-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='context',
            field=models.JSONField(default=dict),
        ),
    ]
