# Generated by Django 5.0.1 on 2024-01-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_chat_context'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
