# Generated by Django 5.0.1 on 2024-01-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='username',
        ),
    ]
